### ISSUE TITLE
Try using DVRPC vector tile services instead of feature services for quicker rendering

### ISSUE THREAD

**Issue by seandoesgis** [brandonfcohen1/phillytrails-app#30]
I'd recommend using DVRPC's vector tiles to increase app performance.

**Pedestrian Network** - https://tiles.dvrpc.org/data/pedestrian-network.json (ped_lines / line_type=1 sidewalks) We are currently working on adding trails to this dataset (line_type=3)

**Bicycle LTS** - https://tiles.dvrpc.org/data/lts.json (use existing conditions layer)

Also, if you could, credit DVRPC as the data sources.  Thanks and great app!

**Comment by brandonfcohen1** [comment]
@seandoesgis thanks for reaching out- will make these changes and add attribution- likely this weekend!

**Comment by brandonfcohen1** [comment]
@seandoesgis - I'm having a hard time getting the tiles to render well in Leaflet. It looks great in Mapbox but struggling with Leaflet, have tried a few libs like https://github.com/Leaflet/Leaflet.VectorGrid

Ever rendered these services in leaflet before?

https://github.com/brandonfcohen1/phillytrails-app/pull/31

**Comment by seandoesgis** [comment]
@crvanpollard at DVRPC mentioned these to try:

- https://gitlab.com/jkuebart/Leaflet.VectorTileLayer/
- https://github.com/SpatialServer/Leaflet.MapboxVectorTile

Thank you for adding attribution!
